# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCZnM7LJbXdNiXLtGqIBZo2cbq0tSp3e

cs104 Lab 1
Name: Lina Abounokaira
Course: CS104-Intro CS Using Python
Lab: Lab One
Date: September 6, 2026

# Part One: Numbers
"""

# Step 1: Ask the user to enter a decimal integer larger than 20
user_number = int(input("Enter a decimal integar larger than 20: "))

# Step 2: Convert the integer to binary using Python's built-in bin() function
binary_value = bin(user_number)
print("Binary representation:", binary_value)

# Step 3: Convert the integer to hexadecimal using Python's built-in hex() function
hex_value = hex(user_number)
print("Hexadecimal representation:", hex_value)

# Step 4: Convert the binary string back to decimal to verify our conversion
binary_back_to_decimal = int(binary_value, 2)
print("Binary converted back to decimal:", binary_back_to_decimal)

# Step 5: Convert the hex string back to decimal to verify our conversion
hex_back_to_decimal = int(hex_value, 16)
print("Hex converted back to decimal:", hex_back_to_decimal)

"""# Part Two: Operators"""

# Step 1: Define the required variables
num_1 = 10
num_2 = 11.0
course_code = "cs104"
course_name = "Intro CS Using Python"
my_name = "Lina Abounokaira"

# Step 2: Print the type of num_1, num_2, and course_name using type()
print("Type of num_1:", type(num_1))
print("Type of num_2:", type(num_2))
print("Type of course_name:", type(course_name))

# Step 3: Multiply num_1 and num_2, store in num_4, then print
num_4 = num_1 * num_2
print("num_4 (num_1 * num_2):", num_4)

# Step 4: Divide num_2 by num_1, store in num_5, then print
num_5 = num_2 / num_1
print("num_5 (num_2 / num_1):", num_5)

# Step 5: Print both the integer part and remainder of num_2 / num_1
integar_part = num_2 // num_1
remainder = num_2 % num_1
print("Integar part of num_2 / num_1:", integar_part)
print("Remainder of num_2 / num_1:", remainder)

# Step 6: Print the final sentence using string concatenation
final_sentence = my_name + " is taking " + course_code.upper() + ": " + course_name
print(final_sentence)